apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-devops-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-devops-app
  template:
    metadata:
      labels:
        app: my-devops-app
    spec:
      containers:
      - name: my-devops-app
        image: 329599640344.dkr.ecr.us-east-1.amazonaws.com/my-devops-app:latest
        ports:
        - containerPort: 5000
